clc
clear all
close all

load('veriseti.mat')



YMatrix1 =h(1:300,1:4);
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 02-Jan-2025 10:01:13

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','a1');
set(plot1(2),'DisplayName','a2');
set(plot1(3),'DisplayName','a3');
set(plot1(4),'DisplayName','a4');

% Create ylabel
ylabel('Vibration (m/s^2)');

% Create xlabel
xlabel('Time (sec)');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontWeight','bold','XGrid','on','XTick',...
    [0 30 60 90 120 150 180 210 240 270 300],'XTickLabel',...
    {'0','1','2','3','4','5','6','7','8','9','10'},'YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.728361464885312 0.549132947976879 0.121856865845981 0.366488203747882]);
